# Generated by Django 5.0.7 on 2024-08-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('design', 'Design'), ('other', 'Other')], max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('certificate1', models.FileField(blank=True, null=True, upload_to='service_certificates/')),
                ('certificate2', models.FileField(blank=True, null=True, upload_to='service_certificates/')),
                ('certificate3', models.FileField(blank=True, null=True, upload_to='service_certificates/')),
                ('certificate4', models.FileField(blank=True, null=True, upload_to='service_certificates/')),
                ('certificate5', models.FileField(blank=True, null=True, upload_to='service_certificates/')),
            ],
        ),
    ]
