# Generated by Django 5.0.7 on 2024-08-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_portfolio_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='date_finish',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
    ]
