# Generated by Django 5.0.7 on 2024-08-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_portfolio_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
